#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE mayan;
    CREATE DATABASE backend;
    GRANT ALL PRIVILEGES ON DATABASE mayan TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE backend TO "$POSTGRES_USER";
EOSQL
